# Задание 1

1) $$(e^{x\,ln(3x+1)})'$$
**Решение:**

Расскроем производную как производную от первой функции и начнем вычислять производную степени:
$${e}^{x\,ln(3x+1)}*(x\,ln(3x+1))'$$
Во второй производной видим произведение двух функций, раскроем ее по правилу произведения:
$${e}^{x\,ln(3x+1)}*((x)'*ln(3x+1)+(ln(3x+1))'*x)$$
Видим, что во второй производной сложная функция от натурального логарифма, расскладываем ее по аналогии с первым пунктом:
$${e}^{x\,ln(3x+1)}*(1*ln(3x+1)+\frac{1}{3x+1}(3x+1)'*x)$$
Вычисляем окончательную производную:
$${e}^{x\,ln(3x+1)}*(1*ln(3x+1)+\frac{1}{3x+1}*3*x)$$
$${e}^{x\,ln(3x+1)}*(1*ln(3x+1)+\frac{3*x}{3x+1})$$

2) $$(e^{x^2}\sqrt{x^3+4x^2-7})'$$
**Решение:**

Видим произведение функций, следовательно, раскроем его как производную от 2 функций:
$$(e^{x^2})'*\sqrt{x^3+4x^2-7}+e^{x^2}*(\sqrt{x^3+4x^2-7})'$$
Видим сложные функции в двух производных. Вычислим их:
$$e^{x^2}*(x^2)'*\sqrt{x^3+4x^2-7}+e^{x^2}*\frac{1}{2\sqrt{x^3+4x^2-7}}*(x^3+4x^2-7)'$$
Вычислим окончательные производные:
$$e^{x^2}*2x*\sqrt{x^3+4x^2-7}+e^{x^2}*\frac{1}{2\sqrt{x^3+4x^2-7}}*(3x^2+8x)$$
$$e^{x^2}*2x*\sqrt{x^3+4x^2-7}+\frac{e^{x^2}*(3x^2+8x)}{2\sqrt{x^3+4x^2-7}}$$

3) $$(\frac{x\sqrt{1-x^2}}{1+x^2})'$$
В данной формуле мы видим деление сложной функции. Разложим его:
$$\frac{(x\sqrt{1-x^2})'*(1+x^2)-(1+x^2)'*(x\sqrt{1-x^2})}{(1+x^2)^2}$$
В первой формуле видим произведение сложных функций. Вычислим его и другую производную:
$$\frac{((x)'*\sqrt{1-x^2}+x*(\sqrt{1-x^2})')*(1+x^2)-2x*(x\sqrt{1-x^2})}{(1+x^2)^2}$$
Расскладываем оставшуюся производную аналогично производной из второго задания:
$$\frac{(1*\sqrt{1-x^2}+x*\frac{1}{2*\sqrt{1-x^2}}*(1-x^2)')*(1+x^2)-2x*(x\sqrt{1-x^2})}{(1+x^2)^2}$$
$$\frac{(\sqrt{1-x^2}+x*\frac{1}{2*\sqrt{1-x^2}}*-2x)*(1+x^2)-2x*(x\sqrt{1-x^2})}{(1+x^2)^2}$$
$$\frac{(\sqrt{1-x^2}+x*\frac{1}{2*\sqrt{1-x^2}}*-2x)*(1+x^2)-2x^2\sqrt{1-x^2}}{(1+x^2)^2}$$

# Задание 2

1) $$u=3x^3+y^2+z^2+6xy-2z+1$$
Вычислим частные производные:
$$\frac{\partial u}{\partial x} = 9x^2+6y$$
$$\frac{\partial u}{\partial y} = 2y+6x$$
$$\frac{\partial u}{\partial z} = 2z-2$$
Решим систему уравнений:
$$\begin{cases}
    9x^2+6y=0 \\
    2y+6x=0 \\
    2z-2=0
\end{cases}$$
$$\begin{cases}
    9x^2+6y=0 \\
    y=-3x \\
    z=1
\end{cases}$$
$$\begin{cases}
    9x^2+6(-3x)=0 \\
    y=-3x \\
    z=1
\end{cases}$$
$$\begin{cases}
    9x^2-18x=0 \\
    y=-3x \\
    z=1
\end{cases}$$
$$\begin{cases}
    x(2-x)=0 \\
    y=-3x \\
    z=1
\end{cases}$$
Из этого образуем 2 системы. Решим первую систему:
$$\begin{cases}
    x=0 \\
    y=-3x \\
    z=1
\end{cases}$$
$$\begin{cases}
    x=0 \\
    y=0 \\
    z=1
\end{cases}$$
Решим вторую систему:
$$\begin{cases}
    x=2 \\
    y=-3x \\
    z=1
\end{cases}$$
$$\begin{cases}
    x=2 \\
    y=-6 \\
    z=1
\end{cases}$$
Итого получили точки (0,0,1) и (2,-6,1)

Для исследования на экстремумы следует взять матрицу Гессе (т. к. 2 точки экстремума, то будет 2 матрицы Гессе):
$$H_1=\left(
    \begin{matrix}
        18*0 & 6 & 0 \\
        6 & 2 & 0 \\
        0 & 0 & 2
    \end{matrix}
\right)$$
$$H_1=\left(
    \begin{matrix}
        0 & 6 & 0 \\
        6 & 2 & 0 \\
        0 & 0 & 2
    \end{matrix}
\right)$$
$$H_2=\left(
    \begin{matrix}
        18*2 & 6 & 0 \\
        6 & 2 & 0 \\
        0 & 0 & 2
    \end{matrix}
\right)$$
$$H_2=\left(
    \begin{matrix}
        36 & 6 & 0 \\
        6 & 2 & 0 \\
        0 & 0 & 2
    \end{matrix}
\right)$$
Найдем угловые миноры для матрицы $H_1$:
$$det_1=0, det_2=-36, det_3=-72$$
Т. к. 0 - неотрицательный, а все остальные числа отрицательные, то можно говорить о том, что в этой точке нет экстремума.
Найдем угловые миноры для матрица $H_2$:
$$det_1=36, det_2 = 36, det_3 = 72$$
Т. к. все миноры положительные, то это точка минимума.

**Ответ**
Точка (0, 0, 1) не является точкой экстремума

Точка (2, -6, 1) является точкой минимума

3) $$z=e^{-x-y}; ограничение: \frac{x^2}{4}+y^2=5$$
Составим функцию Лагранжа:
$$\mathcal L (x, y, \lambda) = e^{-x-y}+\lambda (\frac{x^2}{4}+y^2-5)$$
Найдем частные производные

Производная по x:
$$\frac{\partial \mathcal L}{\partial x} = -e^{-x-y}+\lambda *\frac{x}{2}=0$$
Производная по y:
$$\frac{\partial \mathcal L}{\partial y} = -e^{-x-y}+2\lambda y=0$$
Производная по $\lambda$:
$$\frac{\partial \mathcal L}{\partial \lambda} =\frac{x^2}{4}+y^2-5=0$$

Построим систему уравнений:
$$\begin{cases}
    -e^{-x-y}+\lambda *\frac{x}{2}=0 \\
    -e^{-x-y}+2\lambda y=0 \\
    \frac{x^2}{4}+y^2-5=0
\end{cases}$$

$$\begin{cases}
    \lambda = \frac{2e^{-x-y}}{x} \\
    \lambda= \frac {e^{-x-y}}{2y} \\
    \frac{x^2}{4}+y^2-5=0
\end{cases}$$

$$\begin{cases}
    \lambda = \frac{2e^{-x-y}}{x} \\
    \frac{2e^{-x-y}}{x} = \frac {e^{-x-y}}{2y} \\
    \frac{x^2}{4}+y^2-5=0
\end{cases}$$

$$\begin{cases}
    \lambda = \frac{2e^{-x-y}}{x} \\
    \frac{2}{x} = \frac {1}{2y} \\
    \frac{x^2}{4}+y^2-5=0
\end{cases}$$

$$\begin{cases}
    \lambda = \frac{2e^{-x-y}}{x} \\
    x = 4y \\
    \frac{x^2}{4}+y^2-5=0
\end{cases}$$

$$\begin{cases}
    \lambda = \frac{2e^{-x-y}}{x} \\
    x = 4y \\
    \frac{(4y)^2}{4}+y^2-5=0
\end{cases}$$

$$\begin{cases}
    \lambda = \frac{2e^{-x-y}}{x} \\
    x = 4y \\
    \frac{4y^2}+y^2-5=0
\end{cases}$$

$$\begin{cases}
    \lambda = \frac{2e^{-x-y}}{x} \\
    x = 4y \\
    5y^2 = 5
\end{cases}$$
Следовательно, образуется 2 системы уравнений:
$$\begin{cases}
    \lambda = \frac{e^{-5}}{2} \\
    x = 4 \\
    y = 1
\end{cases}$$
$$\begin{cases}
    \lambda = -\frac{e^{5}}{2} \\
    x = -4 \\
    y = -1
\end{cases}$$
Следовательно, в точке (4, 1) будет минимум функции (т. к. целевая функция принимает значение $e^{-5}$), а в точек (-4, 1) - максимум (т. к. целевая функция принимает значение $e^{5}$)

# Задача 4
Т. к. было сказано в Пачке, что можно использовать готовое решение, то использую его. Ответ в Пачке от 13 января.

In [114]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OrdinalEncoder
from sklearn.naive_bayes import GaussianNB

df = pd.read_csv('./data/task_4.csv')
print('Исходный DF:')
print(df)
encoder = OrdinalEncoder()
df_encoded = encoder.fit_transform(df) # делаем энкодер для текстовых данных

X = df_encoded[:, 0:2] # составляем X и y
y = df_encoded[:, 2]

print('Закодированный DF')
print(df_encoded)

nb_clf = GaussianNB()
X_train, X_test, y_train, y_test = train_test_split(X, y) # разделяем на выборки

nb_clf.fit(X_train, y_train)
nb_clf_pred = nb_clf.predict(X_test) # предсказываем

accuracy = accuracy_score(y_test, nb_clf_pred) # считаем метрику accuracy
print('Оценка модели методом accuracy: ', accuracy)

Исходный DF:
         Test Age_Group        Status
0    Positive     Young      Infected
1    Positive     Young      Infected
2    Positive     Young      Infected
3    Positive       Old      Infected
4    Positive       Old      Infected
..        ...       ...           ...
273  Positive       Old  Not_infected
274  Positive       Old  Not_infected
275  Positive       Old  Not_infected
276  Positive       Old  Not_infected
277  Positive       Old  Not_infected

[278 rows x 3 columns]
Закодированный DF
[[1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 0. 1.]
 [1. 0. 1.]
 [1. 0. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 1.]
 [0. 1. 1.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 0. 1.]
 [1. 0. 1.]
 [1. 0. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 1.]
 [0. 1. 1.]
 [1. 1. 0

# Задание 5
В данном задании уже нельзя использовать встроенные библиотеки Python (к сожалению), делаю метод руками.

Вычисление производных в автоматическом режиме было бы слишком проблематично, поэтому их задаю в виде функций.

In [119]:
def f(x):
    return x**4+3*x**3-12*x**2+7*x-2
def f_der(x):
    return 4*x**3+9*x**2-24*x+7
def f_der_2(x):
    return 12*x**2+18*x-24

x=10
accuracy = 0.0001

while True:
    f_der_for_x = f_der(x)
    f_def_2_for_x = f_der_2(x)
    
    x_new = x - f_der_for_x/f_def_2_for_x
    
    if abs(x_new-x)<accuracy:
        print('Найден экстремум при x=', x_new)
        break
    
    x = x_new

Найден экстремум при x= 1.3101356031490567


# Задание 6

Дана таблица:
| 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 |
| --- | --- | --- | --- | --- | --- | --- | --- |
| 0.1 | 0.3 | 0.1 | 0.25 | 0.05 | 0.05 | 0.1 | ? |

1) Предполагаем, что это полная группа несовместных событий (иначе вероятность найти было бы не возможно). Тогда:
$$P_7 = 1-(0.1+0.3+0.1+0.25+0.05+0.05+0.1) = 0.05$$
2) Найдем матожидание:
$$E(X) = 0.1*0 + 0.3*1 + 0.1*2 + 0.25*3 + 0.05*4 + 0.05*5 + 0.1*6 + 0.05*7 = 2.65$$
3) Найдем дисперсию:
$$E(X^2)=0.1*0^2 + 0.3*1^2 + 0.1*2^2 + 0.25*3^2 + 0.05*4^2 + 0.05*5^2 + 0.1*6^2 + 0.05*7^2 = 11.05$$
$$D(X) = E(X^2)-(E(X))^2 = 11.05 - (2.65)^2 = 4.03$$


# Задание 7

Учитывая данные задачи (а именно то, что известна средняя частота звонков). Следовательно, можно предположить, что мы имеем дело с распределением Пуассона.

В первую очередь рассчитаем количество звонков в час: $\lambda = 16/8 = 2$

Т. к. не может быть 2.5 звонка, а также наблюдения независимы, то можем выразить вероятность того, что поступит не меньше 2 и не больше 4 звонков как сумму вероятностей:
$$P(2\leq X \leq 4) = P(X=2)+P(X=3)+P(X=4)$$

Произведем расчеты:
1. $P(X=2) = \frac{2^2*e^{-2}}{2!} = 2e^{-2}$
2. $P(X=3) = \frac{2^3*e^{-2}}{3!} = \frac{4e^{-2}}{3}$
2. $P(X=3) = \frac{2^4*e^{-2}}{4!} = \frac{2e^{-2}}{3}$

Вычисляем сумму вероятностей:
$$P(2\leq X \leq 4) = 2e^{-2} + \frac{4e^{-2}}{3} + \frac{2e^{-2}}{3} = 4e^{-2}$$

Подставив константу получаем:
$$P(2\leq X \leq 4) = 4*(2.7182)^-2 = 4*\frac{1}{7.3890} = 4*0.1353 = 0.541 = 54.1%$$ 

**Ответ:**
Вероятность поступления от 2 до 4 звонков за час составляет 54.1%